### ISSUE TITLE
make order of includeModules() in template deterministic

### ISSUE THREAD

**Issue by rottaran** [ManyThreads/mcconf#15]
for example sorted by the module names. This should make the generated files more reproducable.

**Comment by kubanrob** [comment]
Note from previous discussion: We may use a topological order based on the dependencies, so that dependent modules can use definitions (or other stuff) provided by their dependencies.

Sorting by module names is still an good idea if there is no more important criterion.

**Comment by rottaran** [comment]
but we can have cyclic dependencies between modules, thus topological order needs a careful implementation. It is better if the design of all modules and templates does not rely on a specific ordering of the modules.
