### ISSUE TITLE
fix tabs in pytoml files

### ISSUE THREAD

**Issue by rottaran** [ManyThreads/mcconf#6]
The newer pytoml parser versions do not like tab characters in strings. Therefore, we rely on the version 0.1.2 and need this install-python-libs script. It would be better, to fix pytoml upstream.

**Comment by rottaran** [comment]
The TOML specification explicitly prohibits tabs and similar control characters in strings in order to be consistent with JSON: https://github.com/toml-lang/toml/issues/474 and https://github.com/toml-lang/toml#user-content-string
The solution would be to use `"""` instead of `'''` and \t instead of tab characters. However, this \t looks plain ugly and difficult to read for our large amounts of makefile fragments.

**Comment by kubanrob** [comment]
Is this still an issue if the main portion of the makefile is generated by an template?

A dirty solution would be to replace every 4 spaces at the beginning of each line in a makefile fragment with a tab. This could be done by the makefile template, and may lead to all kinds of confusions.

I suggest we don't fix it for the time being.
In the long term, we should try to further separate the data (module files) and the view (templates). However, we should not do this without a plan (and documentation) to avoid confusing notations and boilerplate in the module files.

**Comment by rottaran** [comment]
both toml parsers handle tabs correctly now.
